In [65]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
df = pd.read_excel(r'C:\Users\Anshu\Downloads\ZS Case Challenge.xlsx')
d=df.values

In [15]:
d

array([[1, 'Cartoons', '10:00-11:59', 150, 'No', 600, 0, 0, 0, 1],
       [2, 'Sportsevents', '7:00-10:00', 180, 'Yes', 400, 0, 1, 1, 0],
       [3, 'Cartoons', '5:00-7:00', 300, 'No', 300, 0, 0, 0, 0],
       [4, 'Movie', '5:00-7:00', 150, 'Yes', 300, 0, 0, 1, 0],
       [5, 'Sportsevents', '5:00-7:00', 300, 'No', 400, 0, 1, 0, 0],
       [6, 'TV series', '5:00-7:00', 120, 'Yes', 450, 1, 0, 1, 0],
       [7, 'TV series', '7:00-10:00', 90, 'No', 200, 1, 0, 1, 0],
       [8, 'Sportsevents', '7:00-10:00', 150, 'No', 1000, 0, 1, 1, 1],
       [9, 'Sportsevents', '7:00-10:00', 60, 'Yes', 800, 1, 1, 1, 1],
       [10, 'Sportsevents', '10:00-11:59', 90, 'No', 450, 1, 1, 0, 0],
       [11, 'Movie', '10:00-11:59', 60, 'No', 300, 1, 0, 0, 0],
       [12, 'Cartoons', '10:00-11:59', 90, 'Yes', 600, 0, 0, 1, 1],
       [13, 'Movie', '5:00-7:00', 120, 'No', 600, 0, 0, 1, 1],
       [14, 'Sportsevents', '5:00-7:00', 90, 'Yes', 800, 1, 1, 1, 1],
       [15, 'Cartoons', '10:00-11:59', 90, 'No', 500, 0

In [66]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for i in range(6):
    d[:,i] = le.fit_transform(d[:,i])


In [17]:
d

array([[0, 0, 0, 3, 0, 5, 0, 0, 0, 1],
       [1, 2, 2, 4, 1, 2, 0, 1, 1, 0],
       [2, 0, 1, 5, 0, 1, 0, 0, 0, 0],
       [3, 1, 1, 3, 1, 1, 0, 0, 1, 0],
       [4, 2, 1, 5, 0, 2, 0, 1, 0, 0],
       [5, 3, 1, 2, 1, 3, 1, 0, 1, 0],
       [6, 3, 2, 1, 0, 0, 1, 0, 1, 0],
       [7, 2, 2, 3, 0, 7, 0, 1, 1, 1],
       [8, 2, 2, 0, 1, 6, 1, 1, 1, 1],
       [9, 2, 0, 1, 0, 3, 1, 1, 0, 0],
       [10, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [11, 0, 0, 1, 1, 5, 0, 0, 1, 1],
       [12, 1, 1, 2, 0, 5, 0, 0, 1, 1],
       [13, 2, 1, 1, 1, 6, 1, 1, 1, 1],
       [14, 0, 0, 1, 0, 4, 0, 0, 0, 0]], dtype=object)

In [67]:
import numpy as np
from sklearn.model_selection import train_test_split

### Running the regression model for S1 only

In [80]:
X, y = d[:-3, :-4], d[:-3,-4:]
X=X.astype('int')
y=y.astype('int')

In [81]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
X=Scaler.fit_transform(X)


In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
print(X)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
print(X_train,y_train)
print(X_test, y_test)

[[-1.59325501 -1.44115338 -1.22474487  0.39223227 -0.84515425  0.9258201 ]
 [-1.30357228  0.48038446  1.22474487  0.98058068  1.18321596 -0.46291005]
 [-1.01388955 -1.44115338  0.          1.56892908 -0.84515425 -0.9258201 ]
 [-0.72420682 -0.48038446  0.          0.39223227  1.18321596 -0.9258201 ]
 [-0.43452409  0.48038446  0.          1.56892908 -0.84515425 -0.46291005]
 [-0.14484136  1.44115338  0.         -0.19611614  1.18321596  0.        ]
 [ 0.14484136  1.44115338  1.22474487 -0.78446454 -0.84515425 -1.38873015]
 [ 0.43452409  0.48038446  1.22474487  0.39223227 -0.84515425  1.8516402 ]
 [ 0.72420682  0.48038446  1.22474487 -1.37281295  1.18321596  1.38873015]
 [ 1.01388955  0.48038446 -1.22474487 -0.78446454 -0.84515425  0.        ]
 [ 1.30357228 -0.48038446 -1.22474487 -1.37281295 -0.84515425 -0.9258201 ]
 [ 1.59325501 -1.44115338 -1.22474487 -0.78446454  1.18321596  0.9258201 ]]
(8, 6) (4, 6) (8, 4) (4, 4)
[[-1.30357228  0.48038446  1.22474487  0.98058068  1.18321596 -0.462910

# Using RandomForest

In [60]:
model = RandomForestClassifier(random_state=1)
model.fit(X_train, y_train)
yhat = model.predict(X_test)
#evaluate predictions
acc = accuracy_score(y_test, yhat)
print('Accuracy: %.3f' % acc)

Accuracy: 0.250


In [29]:
y1=model.predict(d[-3:, :-4])
print(y1)

[[0 0 1 1]
 [1 1 1 1]
 [0 0 0 1]]


# Using Naive Bayes

In [77]:
from sklearn.naive_bayes import GaussianNB

In [78]:
gnb = GaussianNB()

In [79]:
gnb.fit(X_train, y_train)
yhat = gnb.predict(X_test)
#evaluate predictions
acc = accuracy_score(y_test, yhat)
print('Accuracy: %.3f' % acc)

Accuracy: 0.750


In [83]:
from sklearn import svm

In [85]:
for item in y_train:
    print (item)
    break

[0 1 1 0]


In [86]:
print (y_train)

[[0 1 1 0]
 [1 0 1 0]
 [0 0 0 1]
 [0 1 1 1]
 [0 0 1 1]
 [1 1 0 0]
 [1 1 1 1]
 [1 0 1 0]]


In [111]:
s1=np.zeros((8,1))
s2=np.zeros((8,1))
s3=np.zeros((8,1))
s4=np.zeros((8,1))


In [112]:
i=0
for item in y_train:
    s1[i][0]=item[0]
    i+=1

i=0
for item in y_train:
    s2[i][0]=item[0]
    i+=1
    
i=0
for item in y_train:
    s3[i][0]=item[0]
    i+=1
    
i=0
for item in y_train:
    s4[i][0]=item[0]
    i+=1
    

In [113]:
s1_test=np.zeros((4,1))
s2_test=np.zeros((4,1))
s3_test=np.zeros((4,1))
s4_test=np.zeros((4,1))


In [114]:
i=0
for item in y_test:
    s1_test[i][0]=item[0]
    i+=1

i=0
for item in y_test:
    s2_test[i][0]=item[0]
    i+=1
    
i=0
for item in y_test:
    s3_test[i][0]=item[0]
    i+=1
    
i=0
for item in y_test:
    s4_test[i][0]=item[0]
    i+=1
    

In [116]:
i=0
clf=svm.SVC()
for column in (s1,s2,s3,s4):
    clf.fit(X_train,column)
    yhat = clf.predict(X_test)
    if i==0:
        ytruth=s1_test
    if i==1:
        ytruth=s2_test
    if i==2:
        ytruth=s3_test
    if i==3:
        ytruth=s4_test
    acc = accuracy_score(ytruth, yhat)
    print('Accuracy: %.3f' % acc)
    i+=1
    

Accuracy: 1.000
Accuracy: 1.000
Accuracy: 1.000
Accuracy: 1.000


C:\Users\Anshu\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Anshu\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Anshu\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Anshu\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 